import 'package:pet_pals/models/pet.dart';

List<Pet> dummyPets = [
  Pet(
    name: 'Beau',
    location: 'Los Angeles, CA',
    type: 'Dog',
    breed: 'Corgi',
    age: 4,
    sex: 'Male',
    color: 'Tan & White',
    sterilized: false,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9A8e3yOEryYIsHFI29VOBx1vUvRef4x0nRg&usqp=CAU',
  ),
  Pet(
    name: 'Kebo',
    location: 'San Francisco, CA',
    type: 'Dog',
    breed: 'Pug',
    age: 5,
    sex: 'Male',
    color: 'Black',
    sterilized: true,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShR6qAY1YYpQCYASToWjsz-9xc-qjYWzr0uA&usqp=CAU',
  ),
  Pet(
    name: 'Nia',
    location: 'New York, NY',
    type: 'Dog',
    breed: 'Mixed',
    age: 2,
    sex: 'Female',
    color: 'White',
    sterilized: true,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfm7vMqDRu1LKveL1dYqK2bx-iCrWa40FCNQ&usqp=CAU',
  ),
  Pet(
    name: 'Tipsy',
    location: 'Seattle, WA',
    type: 'Dog',
    breed: 'Shih tzu',
    age: 3,
    sex: 'Female',
    color: 'white',
    sterilized: true,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnDO-fiT9BHhY4J4tFgVWtgMmqwSXxIIP90bq_rJwygHD_cq6rSXtfEDVTdPStRGLYzZo&usqp=CAU',
  ),
  Pet(  
    name: 'Buddy',
    location: 'Denver, CO',
    type: 'Dog',
    breed: 'Golden Retriever',
    age: 7,
    sex: 'Male',
    color: 'Golden',
    sterilized: true,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9iG3xUX1V0yfx-4W8YO9HdYWKm1BvFxVtNQ&usqp=CAU',
  ),
];
