// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLqYYHC7Hkm-JfWLDm_AE5YCP1HLJVHVQ',
    appId: '1:1069943460237:web:e3bb7212f22de078f4adc4',
    messagingSenderId: '1069943460237',
    projectId: 'petpals-9935f',
    authDomain: 'petpals-9935f.firebaseapp.com',
    storageBucket: 'petpals-9935f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6fSmQZ0ViRXtOWEvyxTRoZYJcRawkTIY',
    appId: '1:1069943460237:android:3b79636daaea14a5f4adc4',
    messagingSenderId: '1069943460237',
    projectId: 'petpals-9935f',
    storageBucket: 'petpals-9935f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJ39fXfSVRa0a2NXeAxVoqwrvYOHgnuo',
    appId: '1:1069943460237:ios:e71d09341572a55cf4adc4',
    messagingSenderId: '1069943460237',
    projectId: 'petpals-9935f',
    storageBucket: 'petpals-9935f.appspot.com',
    iosBundleId: 'com.example.petPals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClJ39fXfSVRa0a2NXeAxVoqwrvYOHgnuo',
    appId: '1:1069943460237:ios:2326d091e9c7254ef4adc4',
    messagingSenderId: '1069943460237',
    projectId: 'petpals-9935f',
    storageBucket: 'petpals-9935f.appspot.com',
    iosBundleId: 'com.example.petPals.RunnerTests',
  );
}
